### PR TITLE
Update Array cops to enforce the bracket style

### PR DESCRIPTION
**Pull request by chrisradford**
Since we do not want to use the %i[ and %w[ versions of the symbol and word array operators, but instead prefer the [:symbol] and ['string'] styles, we should set the cop to enforce those rather than disabling it.

@ljones140 @budmc29 any reason not to do this? (following on from #17 and addressing #20)

### CODE REVIEW

**Comment by budmc29** [comment]
@simplybusiness/developers

**Comment by budmc29** [comment]
Good point, maybe we need to create a PR to address all the offences this will generate before merging this? Most likely the next build will fail if someone merges without pulling from this one 🤔.

**Comment by apeacock1991** [comment]
Ironically, Semaphore failed 😅

```
lib/simplycop/security/reject_all_requests_local.rb:3:17: C: Style/WordArray: Use [] for an array of words. (https://rubystyle.guide#percent-w)
--
139 | RAILS_ENV = %w[integration staging production]
139 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
140 |  
142 | 19 files inspected, 1 offense detected
```

**Comment by apeacock1991** [comment]
I've preemptively fixed the issues in https://github.com/simplybusiness/chopin/pull/14897. Pointed to the SimplyCop branch locally and fixed all the issues.

**Pull request merged**
