### PR TITLE
Remove array cops

### PR DESCRIPTION
**Pull request by ljones140**
# What it Does

Disables :
Style::SymbolArray
Style::WordArray

# Why
`%s[foo]` is not better than `[:foo]`
The latter makes it more obvious `:foo` is a symbol

`%w[foo]` is not better than `['foo']`
The latter makes it obvious the elements are strings.
If a word containing a space is added, we have to change the whole array
to the conventional array declaration.

### CODE REVIEW

**Comment by budmc29** [comment]
@simplybusiness/developers speak now or forever hold your peace 😂

**Comment by ljones140** [comment]
> @simplybusiness/developers speak now or forever hold your peace 😂

Why have you released the hounds upon me 😢

**Comment by budmc29** [comment]
Sorry @ljones140 we need to be fair 😅

**Comment by rafal-brize** [comment]
If we switch it off then the code will be less coherent.
It will be possible for people to use one version AND the other. 
I personally prefer consistency and i am totally used to `%{}` shortcuts and don't mind them.
My IDE actually takes care of doing that for me!

plus you can squeeze more of those within a line.

**Comment by ljones140** [comment]
> If we switch it off then the code will be less coherent.
> It will be possible for people to use one version AND the other.
> I personally prefer consistency and i am totally used to `%{}` shortcuts and don't mind them.
> My IDE actually takes care of doing that for me!
> 
> plus you can squeeze more of those within a line.

@rafal-brize `%w` does not offer consistency as if you have a string containing a space you cannot use it. So you have to use standard array notation `[]` for any of them.

**Comment by rafal-brize** [comment]
> > If we switch it off then the code will be less coherent.
> > It will be possible for people to use one version AND the other.
> > I personally prefer consistency and i am totally used to `%{}` shortcuts and don't mind them.
> > My IDE actually takes care of doing that for me!
> > plus you can squeeze more of those within a line.
> 
> @rafal-brize `%w` does not offer consistency as if you have a string containing a space you cannot use it. So you have to use standard array notation `[]` for any of them.

Fair enough, didn't think about that.

**Comment by chrisradford** [comment]
@ljones140 Any reason we disabled the cop rather than just enforcing the style we want?

```ruby
EnforcedStyle: brackets
```

https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/SymbolArray

**Comment by ljones140** [comment]
@chrisradford becuase I did not know that you could do that.
Sounds like a good idea

**Pull request merged**
